### ISSUE TITLE
[Bug] Can't import playlist from different users

### ISSUE THREAD

**Issue by technoize** [yaronzz/Suda#2]
I can't seem to import spotify playlist from different users. It gave me an error.

Sample: https://open.spotify.com/playlist/4pkB7Eyaky2Rl9MZ0DCPib

![image](https://user-images.githubusercontent.com/66208373/89115497-695e9300-d4bb-11ea-9f3d-2926c48094d8.png)

**Comment by yaronzz** [comment]
The first track is a episode.
Next version will skip some tracks which are episode

**Comment by alex5908** [comment]
How shall I install this program? I don't see any exe file.
